version: '3.1'
services:
  film-tracker:
    image: winmord/film-tracker:latest
    container_name: film-tracker
    depends_on:
      - film-tracker-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://film-tracker-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - KINOPOISK_API_KEY=${KINOPOISK_API_KEY}

  film-tracker-db:
    image: postgres:12
    container_name: film-tracker-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}